name: ProcessingLists
on:
  schedule:
    - cron: "0 0/12 * * *" # Runs every 12 hours (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: node20
      - name: Use Node.js
      - run: node writeFile.js 
      - run: node process_AIP-Alpha7-latest.js
      - name: Commit & Push
        uses: actions-x/commit@v6
