name: ProcessingLists
on:
  schedule:
    - cron: "0 0/12 * * *" # Runs every 12 hours (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: node writeFile.js 
      - run: node process_AIP-Alpha7-latest.js
      - run: node process_s_drop.js
      - run: node process_dshield.js
      - name: Commit & Push
        uses: actions-x/commit@v6
