name: Processing_Hagezi_TLD_lists
on:
  schedule:
    - cron: "0 0/12 * * *" # Runs every 12 hours (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node20
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: node processed_spam_tlds_adblock.js
      - run: node processed_spam_tlds_adblock_aggressive.js
      - run: node processed_spam_tlds_adblock_allow.js
      - name: Commit & Push
        uses: actions-x/commit@v6
