name: ProcessingLists
on:
  schedule:
    - cron: "0 0/8 * * *" # Runs every 08 hours (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Deploy
        env:
          GREYNOISE_API_TOKEN: ${{ secrets.GREYNOISE_API_TOKEN }}
        run: |
          curl -X POST https://api.greynoise.io/v3/tags/869feaa1-dc77-4037-aee2-247b7a39cf7d/ips?format=txt&token=cyAPZPxaSCucY81X7eTSPg \
          -H "Authorization: Bearer $GREYNOISE_API_TOKEN" \
          -d '{"ref": "main"}'
      - run: node writeFile.js 
      - run: node process_AIP-Alpha7-latest.js
      - run: node process_s_drop.js
      - run: node process_dshield.js
      - name: Commit & Push
        uses: actions-x/commit@v6
